params:
    fastp:
      min_len : 30 # Recommended value >= 30
    rmhost:
      bowtie2_index : "/ldfssz1/ST_META/share/User/tianliu/database/bowtie2_index/hg38/hg38" #hg38.p13
      threads: 8
    metaphlan3:
      bowtie2db: "/ldfssz1/ST_META/share/User/tianliu/database/metaphlan"
      index: "mpa_v30_CHOCOPhlAn_201901"
      threads: 8

assay:
    trimming: "1.assay/01.trimming"
    rmhost: "1.assay/02.rmhost"
    profile: "1.assay/03.profile/metaphlan3"

results:
    "2.result"

logs:
    trimming: "1.assay/logs/01.trimming"
    rmhost: "1.assay/logs/02.rmhost"
