params:
    fastp:
      min_len : 30 # Recommended value >= 30
    rmhost:
      bowtie2_index : "/ldfssz1/ST_META/P18Z10200N0127_VC/tianliu/test/meta_assemble/bowtie2_index/Horse/Horse_bw2_index" 
      threads: 8
    metaphlan3:
      path: "/ldfssz1/ST_META/P18Z10200N0127_VC/tianliu/bin/tools/metaphlan3" #请将整个mp3文件夹复制到自己的工作路径下并更新此处路径。
      threads: 4

assay:
    trimming: "1.assay/01.trimming"
    rmhost: "1.assay/02.rmhost"
    profile: "1.assay/03.profile/metaphlan3"

results:
    "2.result"

logs:
    trimming: "1.assay/logs/01.trimming"
    rmhost: "1.assay/logs/02.rmhost"